from python:3.6-slim

RUN apt-get update 
RUN apt-get upgrade -y
RUN apt install cron -y

RUN pip install pip --upgrade
RUN pip install django==1.11
RUN pip install djangorestframework
RUN pip install django-admin-rangefilter
RUN pip install requests
RUN pip install savoir
RUN pip install psycopg2-binary
RUN pip install django-jet
RUN pip install mailchimp3
RUN pip install gunicorn
RUN pip install sentry-sdk

RUN python --version


 # docker build -t clmanap_django . 
